module datapath (
    output wire ALU_F,
    output wire ALU_Z,
    output wire ALU_N,
    output wire [15:0] RDST,
    output wire [15:0] DMEM_ADDR,
    output wire [15:0] PC,
    output wire [15:0] INSTR,
    input wire VSS,
    input wire VDD,
    input wire [15:0] RA,
    input wire [15:0] RB,
    input wire [15:0] DMEM_Q,
    input wire [15:0] WE,
    input wire [15:0] IMEM_Q,
    input wire ALU_SRC_B,
    input wire ALU_SRC_A,
    input wire IS_LUI,
    input wire SHIFT_VAL_SRC,
    input wire [1:0] ALU_SEL,
    input wire REG_WRITE,
    input wire ALU_CIN,
    input wire PC_BR,
    input wire PC_JMP,
    input wire CLK,
    input wire RSTn,
    input wire EXTEND,
    input wire SHIFT_AMT_SRC,
    input wire SI,
    input wire SE,
    input wire [3:0] DATA_OUT
);
  // Implemented using datapath.sch and SpiceBind
endmodule
