// module datapath (
// output wire ALU_F,
// output wire ALU_Z,
// output wire ALU_N,
// output wire [15:0] RDST,
// output wire [15:0] DMEM_ADDR,
// output wire [15:0] PC,
// output wire [15:0] INSTR,
// input wire VSS,
// input wire VDD,
// input wire [15:0] RA,
// input wire [15:0] RB,
// input wire [15:0] DMEM_Q,
// input wire [15:0] WE,
// input wire [15:0] IMEM_Q,
// input wire ALU_SRC_B,
// input wire ALU_SRC_A,
// input wire IS_LUI,
// input wire SHIFT_VAL_SRC,
// input wire [1:0] ALU_SEL,
// input wire REG_WRITE,
// input wire ALU_CIN,
// input wire PC_BR,
// input wire PC_JMP,
// input wire CLK,
// input wire RSTn,
// input wire EXTEND,
// input wire SHIFT_AMT_SRC,
// input wire SI,
// input wire SE,
// input wire [3:0] DATA_OUT
// );
// // Implemented using datapath.sch and SpiceBind
// endmodule
module datapath (
    // Single-bit outputs
    output wire ALU_F,
    output wire ALU_Z,
    output wire ALU_N,

    // RDST [15:0]
    output wire RDST15,
    output wire RDST14,
    output wire RDST13,
    output wire RDST12,
    output wire RDST11,
    output wire RDST10,
    output wire RDST9,
    output wire RDST8,
    output wire RDST7,
    output wire RDST6,
    output wire RDST5,
    output wire RDST4,
    output wire RDST3,
    output wire RDST2,
    output wire RDST1,
    output wire RDST0,

    // DMEM_ADDR [15:0]
    output wire DMEM_ADDR15,
    output wire DMEM_ADDR14,
    output wire DMEM_ADDR13,
    output wire DMEM_ADDR12,
    output wire DMEM_ADDR11,
    output wire DMEM_ADDR10,
    output wire DMEM_ADDR9,
    output wire DMEM_ADDR8,
    output wire DMEM_ADDR7,
    output wire DMEM_ADDR6,
    output wire DMEM_ADDR5,
    output wire DMEM_ADDR4,
    output wire DMEM_ADDR3,
    output wire DMEM_ADDR2,
    output wire DMEM_ADDR1,
    output wire DMEM_ADDR0,

    // PC [15:0]
    output wire PC15,
    output wire PC14,
    output wire PC13,
    output wire PC12,
    output wire PC11,
    output wire PC10,
    output wire PC9,
    output wire PC8,
    output wire PC7,
    output wire PC6,
    output wire PC5,
    output wire PC4,
    output wire PC3,
    output wire PC2,
    output wire PC1,
    output wire PC0,

    // INSTR [15:0]
    output wire INSTR15,
    output wire INSTR14,
    output wire INSTR13,
    output wire INSTR12,
    output wire INSTR11,
    output wire INSTR10,
    output wire INSTR9,
    output wire INSTR8,
    output wire INSTR7,
    output wire INSTR6,
    output wire INSTR5,
    output wire INSTR4,
    output wire INSTR3,
    output wire INSTR2,
    output wire INSTR1,
    output wire INSTR0,

    // Power
    input wire VSS,
    input wire VDD,

    // RA [15:0]
    input wire RA15,
    input wire RA14,
    input wire RA13,
    input wire RA12,
    input wire RA11,
    input wire RA10,
    input wire RA9,
    input wire RA8,
    input wire RA7,
    input wire RA6,
    input wire RA5,
    input wire RA4,
    input wire RA3,
    input wire RA2,
    input wire RA1,
    input wire RA0,

    // RB [15:0]
    input wire RB15,
    input wire RB14,
    input wire RB13,
    input wire RB12,
    input wire RB11,
    input wire RB10,
    input wire RB9,
    input wire RB8,
    input wire RB7,
    input wire RB6,
    input wire RB5,
    input wire RB4,
    input wire RB3,
    input wire RB2,
    input wire RB1,
    input wire RB0,

    // DMEM_Q [15:0]
    input wire DMEM_Q15,
    input wire DMEM_Q14,
    input wire DMEM_Q13,
    input wire DMEM_Q12,
    input wire DMEM_Q11,
    input wire DMEM_Q10,
    input wire DMEM_Q9,
    input wire DMEM_Q8,
    input wire DMEM_Q7,
    input wire DMEM_Q6,
    input wire DMEM_Q5,
    input wire DMEM_Q4,
    input wire DMEM_Q3,
    input wire DMEM_Q2,
    input wire DMEM_Q1,
    input wire DMEM_Q0,

    // WE [15:0]
    input wire WE15,
    input wire WE14,
    input wire WE13,
    input wire WE12,
    input wire WE11,
    input wire WE10,
    input wire WE9,
    input wire WE8,
    input wire WE7,
    input wire WE6,
    input wire WE5,
    input wire WE4,
    input wire WE3,
    input wire WE2,
    input wire WE1,
    input wire WE0,

    // IMEM_Q [15:0]
    input wire IMEM_Q15,
    input wire IMEM_Q14,
    input wire IMEM_Q13,
    input wire IMEM_Q12,
    input wire IMEM_Q11,
    input wire IMEM_Q10,
    input wire IMEM_Q9,
    input wire IMEM_Q8,
    input wire IMEM_Q7,
    input wire IMEM_Q6,
    input wire IMEM_Q5,
    input wire IMEM_Q4,
    input wire IMEM_Q3,
    input wire IMEM_Q2,
    input wire IMEM_Q1,
    input wire IMEM_Q0,

    // ALU_SEL [1:0]
    input wire ALU_SEL1,
    input wire ALU_SEL0,

    // DATA_OUT [3:0]
    input wire DATA_OUT3,
    input wire DATA_OUT2,
    input wire DATA_OUT1,
    input wire DATA_OUT0,

    // Single-bit inputs
    input wire ALU_SRC_B,
    input wire ALU_SRC_A,
    input wire IS_LUI,
    input wire SHIFT_VAL_SRC,
    input wire REG_WRITE,
    input wire ALU_CIN,
    input wire PC_BR,
    input wire PC_JMP,
    input wire CLK,
    input wire RSTn,
    input wire EXTEND,
    input wire SHIFT_AMT_SRC,
    input wire SI,
    input wire SE
);
  // Implemented using datapath.sch and SpiceBind
endmodule
