import sys
import os
import re
import numpy as np
from vcd import VCDWriter

# 3.3V Logic Threshold
V_TH = 1.65


def clean_trace_name(name):
    if name.lower().startswith("v(") and name.endswith(")"):
        return name[2:-1]
    return name


def convert_all_raw_to_vcd_fast(raw_filename, keep_analog_reals=False):
    vcd_filename = os.path.splitext(raw_filename)[0] + ".vcd"

    print("Parsing SPICE header directly...")

    num_vars = 0
    num_points = 0
    variables = []
    data_offset = 0

    # 1. Parse the header manually to find data dimensions and variables
    with open(raw_filename, "rb") as f:
        while True:
            line = f.readline().decode("ascii", errors="ignore").strip()

            if line.startswith("No. Variables:"):
                num_vars = int(line.split(":")[1].strip())
            elif line.startswith("No. Points:"):
                num_points = int(line.split(":")[1].strip())
            elif line == "Variables:":
                for _ in range(num_vars):
                    var_line = f.readline().decode("ascii", errors="ignore").strip()
                    # Format: index, name, type
                    parts = var_line.split()
                    variables.append(parts[1])
            elif line == "Binary:":
                data_offset = f.tell()
                break
            elif line == "Values:":
                print(
                    "Error: This script is optimized for Binary raw files, but this is ASCII."
                )
                return

    print(
        f"Header parsed. File contains {num_vars} variables and {num_points} time steps."
    )

    # 2. Map EVERY trace name to its column index
    bus_pattern = re.compile(r"^(.*?)[\[\(_-]?(\d+)[\]\)_]*([a-zA-Z_]*|\.data)$")

    buses_temp = {}
    scalars = {}
    time_idx = None

    for idx, raw_name in enumerate(variables):
        if raw_name == "time":
            time_idx = idx
            continue

        cname = clean_trace_name(raw_name)
        match = bus_pattern.match(cname)

        if match:
            prefix, bit_str, suffix = match.groups()
            bit_idx = int(bit_str)

            base = prefix + suffix

            if base not in buses_temp:
                buses_temp[base] = {}
            buses_temp[base][bit_idx] = idx
        else:
            scalars[raw_name] = idx

    # Filter single-bit buses back to scalars
    buses = {}
    for base, bits in buses_temp.items():
        if len(bits) > 1:
            buses[base] = bits
        else:
            single_trace = list(bits.keys())[0]
            scalars[variables[bits[single_trace]]] = bits[single_trace]

    if time_idx is None:
        print("Error: 'time' variable not found in raw file.")
        return

    if keep_analog_reals:
        print(f"Grouped into {len(buses)} digital buses and {len(scalars)} analog scalars (keeping as reals).")
    else:
        print(f"Grouped into {len(buses)} digital buses and {len(scalars)} analog scalars (converting to 1-bit wires).")

    # 3. Memory-Map the binary payload (0 MB RAM overhead)
    print("Memory-mapping binary payload...")
    raw_data = np.memmap(
        raw_filename,
        dtype=np.float64,
        mode="r",
        offset=data_offset,
        shape=(num_points, num_vars),
    )

    # 4. Write ALL data to VCD
    print(f"Writing {vcd_filename}... (This might take a moment due to sheer volume)")
    with open(vcd_filename, "w") as f:
        writer = VCDWriter(f, timescale="1 ps", date="Generated by fast raw2vcd")
        vcd_vars = {}

        # Register all buses
        for base, bits in buses.items():
            max_idx = max(bits.keys())
            vcd_vars[base] = writer.register_var(
                scope="ngspice", name=base, var_type="wire", size=max_idx + 1
            )

        # Register all scalars
        for trace_name in scalars.keys():
            cname = clean_trace_name(trace_name)
            if keep_analog_reals:
                vcd_vars[trace_name] = writer.register_var(
                    scope="ngspice", name=cname, var_type="real", size=64
                )
            else:
                vcd_vars[trace_name] = writer.register_var(
                    scope="ngspice", name=cname, var_type="wire", size=1
                )

        percent_interval = max(1, num_points // 10)

        # Loop through the time steps, pulling directly from the memmap
        for i in range(num_points):
            if i % percent_interval == 0:
                print(f"Progress: {(i/num_points)*100:.0f}%...")

            t_ps = int(raw_data[i, time_idx] * 1e12)

            # Write buses
            for base, bits in buses.items():
                bus_size = max(bits.keys()) + 1
                bus_val_list = ["x"] * bus_size

                for bit_idx, col_idx in bits.items():
                    val = raw_data[i, col_idx]
                    bus_val_list[bus_size - 1 - bit_idx] = "1" if val >= V_TH else "0"

                writer.change(vcd_vars[base], t_ps, "".join(bus_val_list))

            # Write scalars
            for trace_name, col_idx in scalars.items():
                val = raw_data[i, col_idx]
                if keep_analog_reals:
                    writer.change(vcd_vars[trace_name], t_ps, val)
                else:
                    bit_val = "1" if val >= V_TH else "0"
                    writer.change(vcd_vars[trace_name], t_ps, bit_val)

    # Clean up the memmap object
    del raw_data
    print("100% - Conversion complete!")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python raw2vcd.py [--keep-analog-reals] <input.raw>")
        sys.exit(1)
    
    keep_analog_reals = "--keep-analog-reals" in sys.argv
    raw_filename = sys.argv[-1]
    
    convert_all_raw_to_vcd_fast(raw_filename, keep_analog_reals)
